[workspace]
resolver = "2"
members = ["mkwsconfig", "wsinit", "profile", "paths", "settings"]

[workspace.package]
version = "0.1.3"
authors = ["lI15SO0"]
description = "An easy way to init workspace."
